"""Unit tests for Acquire-By-Hash index copies in Manifest.write_to_s3().

apt advertises support for by-hash in the Release file (``Acquire-By-Hash:
yes``). When enabled, apt fetches each index from
``<index-dir>/by-hash/<NAME>/<hash>`` instead of the plain path. These tests
verify pydeb-s3 publishes those content-addressed copies for every hash
section it emits (SHA256, SHA512, MD5Sum).

MockS3Adapter is used with no prefix so its internal ``_storage`` keys are
identical to the S3 keys. ``Packages.gz`` is compared as bytes because
``MockS3Adapter.read()`` assumes UTF-8.
"""

import gzip
import struct

import pytest

from pydeb_s3 import manifest as manifest_module
from pydeb_s3 import package as package_module
from pydeb_s3.s3_adapter import MockS3Adapter

INDEX_DIR = "dists/stable/main/binary-amd64"
PACKAGES_KEY = f"{INDEX_DIR}/Packages"
PACKAGES_GZ_KEY = f"{INDEX_DIR}/Packages.gz"


class _RecordingAdapter:
    """Minimal adapter that records store_file calls and fakes exists()."""

    def __init__(self, existing=None):
        self.stored: list[tuple[str, dict]] = []
        self._existing = set(existing or [])

    def exists(self, key: str) -> bool:
        return key in self._existing

    def store_file(self, filepath, key, **kwargs):
        self.stored.append((key, kwargs))


def _by_hash_key(index_key: str, name: str, value: str) -> str:
    directory = index_key.rsplit("/", 1)[0]
    return f"{directory}/by-hash/{name}/{value}"


@pytest.fixture
def adapter():
    return MockS3Adapter(bucket="test-bucket")


@pytest.fixture
def written(adapter, sample_deb_file):
    """Write a one-package manifest and return (manifest, adapter)."""
    pkg = package_module.Package.parse_file(sample_deb_file)
    manifest = manifest_module.Manifest(codename="stable", component="main", architecture="amd64")
    manifest.add(pkg)
    manifest.write_to_s3(adapter)
    return manifest, adapter


class TestManifestByHash:
    """Tests for by-hash copies generated by Manifest.write_to_s3()."""

    def test_packages_by_hash_keys_exist_for_all_algorithms(self, written):
        """by-hash copies exist for Packages for every emitted hash type."""
        manifest, adapter = written
        hashes = manifest.files["main/binary-amd64/Packages"]
        for algo, name in manifest_module._BY_HASH_DIRS:
            key = _by_hash_key(PACKAGES_KEY, name, hashes[algo])
            assert adapter.exists(key), f"Missing by-hash key: {key}"

    def test_packages_gz_by_hash_keys_exist_for_all_algorithms(self, written):
        """by-hash copies exist for Packages.gz for every emitted hash type."""
        manifest, adapter = written
        hashes = manifest.files["main/binary-amd64/Packages.gz"]
        for algo, name in manifest_module._BY_HASH_DIRS:
            key = _by_hash_key(PACKAGES_GZ_KEY, name, hashes[algo])
            assert adapter.exists(key), f"Missing by-hash key: {key}"

    def test_by_hash_content_equals_plain_packages(self, written):
        """Each Packages by-hash copy is byte-identical to the plain index."""
        manifest, adapter = written
        plain = adapter._storage[PACKAGES_KEY]
        hashes = manifest.files["main/binary-amd64/Packages"]
        for algo, name in manifest_module._BY_HASH_DIRS:
            key = _by_hash_key(PACKAGES_KEY, name, hashes[algo])
            assert adapter._storage[key] == plain

    def test_by_hash_content_equals_plain_packages_gz(self, written):
        """Each Packages.gz by-hash copy is byte-identical to the plain index."""
        manifest, adapter = written
        plain = adapter._storage[PACKAGES_GZ_KEY]
        hashes = manifest.files["main/binary-amd64/Packages.gz"]
        for algo, name in manifest_module._BY_HASH_DIRS:
            key = _by_hash_key(PACKAGES_GZ_KEY, name, hashes[algo])
            assert adapter._storage[key] == plain

    def test_apt_gateway_sha512_path_exists_for_packages_gz(self, written):
        """The exact SHA512 URI apt requests for Packages.gz resolves."""
        manifest, adapter = written
        hashes = manifest.files["main/binary-amd64/Packages.gz"]
        key = _by_hash_key(PACKAGES_GZ_KEY, "SHA512", hashes["sha512"])
        assert adapter.exists(key), f"apt by-hash gateway missing: {key}"
        assert adapter._storage[key] == adapter._storage[PACKAGES_GZ_KEY]

    def test_by_hash_dir_names_are_canonical_uppercase(self, written):
        """Only the canonical uppercase algorithm directory names are used."""
        _, adapter = written
        contents, _ = adapter.list_objects(f"{INDEX_DIR}/by-hash/")
        names = {obj["Key"].split("/")[-2] for obj in contents}
        assert names == {"SHA256", "SHA512", "MD5Sum"}

    def test_by_hash_keys_not_added_to_manifest_files(self, written):
        """by-hash keys must never leak into the Release hash sections."""
        manifest, _ = written
        assert all("by-hash" not in key for key in manifest.files), manifest.files

    def test_by_hash_content_type_matches_plain_index(self, written):
        """by-hash objects carry the same content type as the plain index."""
        manifest, adapter = written
        pkg_hashes = manifest.files["main/binary-amd64/Packages"]
        gz_hashes = manifest.files["main/binary-amd64/Packages.gz"]

        assert adapter._metadata[PACKAGES_KEY]["ContentType"].startswith("text/plain")
        assert adapter._metadata[PACKAGES_GZ_KEY]["ContentType"].startswith("application/x-gzip")

        for algo, name in manifest_module._BY_HASH_DIRS:
            pkg_key = _by_hash_key(PACKAGES_KEY, name, pkg_hashes[algo])
            gz_key = _by_hash_key(PACKAGES_GZ_KEY, name, gz_hashes[algo])
            assert (
                adapter._metadata[pkg_key]["ContentType"]
                == adapter._metadata[PACKAGES_KEY]["ContentType"]
            )
            assert (
                adapter._metadata[gz_key]["ContentType"]
                == adapter._metadata[PACKAGES_GZ_KEY]["ContentType"]
            )

    def test_uses_store_file_not_copy(self, adapter, sample_deb_file):
        """by-hash copies go through store_file (ACL-preserving), never copy()."""
        calls = {"copy": [], "store_file": []}
        original_copy = adapter.copy
        original_store = adapter.store_file

        def tracking_copy(*args, **kwargs):
            calls["copy"].append(args)
            return original_copy(*args, **kwargs)

        def tracking_store(filepath, key, **kwargs):
            if "/by-hash/" in key:
                calls["store_file"].append(key)
            return original_store(filepath, key, **kwargs)

        adapter.copy = tracking_copy
        adapter.store_file = tracking_store

        pkg = package_module.Package.parse_file(sample_deb_file)
        manifest = manifest_module.Manifest(
            codename="stable", component="main", architecture="amd64"
        )
        manifest.add(pkg)
        manifest.write_to_s3(adapter)

        assert calls["copy"] == [], "copy() drops the public-read ACL and must not be used"
        assert len(calls["store_file"]) == 2 * len(manifest_module._BY_HASH_DIRS)

    def test_by_hash_written_even_when_skip_package_upload(self, adapter, sample_deb_file):
        """Index metadata is written regardless of whether the .deb is uploaded."""
        pkg = package_module.Package.parse_file(sample_deb_file)
        manifest = manifest_module.Manifest(
            codename="stable",
            component="main",
            architecture="amd64",
            skip_package_upload=True,
        )
        manifest.add(pkg)
        manifest.write_to_s3(adapter)

        for file_key in ("main/binary-amd64/Packages", "main/binary-amd64/Packages.gz"):
            hashes = manifest.files[file_key]
            for algo, name in manifest_module._BY_HASH_DIRS:
                assert adapter.exists(
                    _by_hash_key(f"{INDEX_DIR}/{file_key.rsplit('/', 1)[1]}", name, hashes[algo])
                )

    def test_by_hash_prefix_handling(self, sample_deb_file):
        """by-hash copies resolve under a configured S3 prefix."""
        prefixed = MockS3Adapter(bucket="test-bucket", prefix="apt")
        pkg = package_module.Package.parse_file(sample_deb_file)
        manifest = manifest_module.Manifest(
            codename="stable", component="main", architecture="amd64"
        )
        manifest.add(pkg)
        manifest.write_to_s3(prefixed)

        hashes = manifest.files["main/binary-amd64/Packages.gz"]
        key = _by_hash_key(PACKAGES_GZ_KEY, "SHA512", hashes["sha512"])
        assert prefixed.exists(key), f"Missing prefixed by-hash key: {key}"
        # Sanity: the underlying storage key carries the prefix.
        assert f"apt/{key}" in prefixed._storage


class TestWriteByHashHelper:
    """Direct unit tests for Manifest._write_by_hash()."""

    def test_maps_all_emitted_algorithms_and_skips_sha1(self):
        """Returns keys for SHA256/SHA512/MD5Sum only, ignoring unadvertised SHA1."""
        adapter = _RecordingAdapter()
        hashes = {
            "sha256": "a" * 64,
            "sha512": "b" * 128,
            "md5": "c" * 32,
            "sha1": "d" * 40,
        }
        manifest_module.Manifest()._write_by_hash(
            adapter, "/tmp/index", PACKAGES_KEY, hashes, "text/plain"
        )

        keys = [key for key, _ in adapter.stored]
        assert keys == [
            _by_hash_key(PACKAGES_KEY, "SHA256", "a" * 64),
            _by_hash_key(PACKAGES_KEY, "SHA512", "b" * 128),
            _by_hash_key(PACKAGES_KEY, "MD5Sum", "c" * 32),
        ]
        assert all("SHA1/" not in key for key in keys)

    def test_skips_existing_content_addressed_objects(self):
        """An already-present by-hash object is not re-uploaded."""
        existing = _by_hash_key(PACKAGES_KEY, "SHA256", "a" * 64)
        adapter = _RecordingAdapter(existing=[existing])
        hashes = {"sha256": "a" * 64, "sha512": "b" * 128, "md5": "c" * 32}

        manifest_module.Manifest()._write_by_hash(
            adapter, "/tmp/index", PACKAGES_KEY, hashes, "text/plain"
        )

        keys = [key for key, _ in adapter.stored]
        assert existing not in keys
        assert len(keys) == 2

    def test_missing_hashes_are_skipped(self):
        """Hash types absent from the dict produce no by-hash uploads."""
        adapter = _RecordingAdapter()
        manifest_module.Manifest()._write_by_hash(
            adapter, "/tmp/index", PACKAGES_KEY, {"sha256": "a" * 64}, "text/plain"
        )
        assert len(adapter.stored) == 1


class TestPackagesGzDeterminism:
    """Packages.gz must be byte-reproducible so by-hash keys are stable."""

    def test_packages_gz_is_deterministic(self, sample_deb_file):
        """Two identical uploads produce identical Packages.gz bytes."""
        outputs = []
        for _ in range(2):
            adapter = MockS3Adapter(bucket="test-bucket")
            pkg = package_module.Package.parse_file(sample_deb_file)
            manifest = manifest_module.Manifest(
                codename="stable", component="main", architecture="amd64"
            )
            manifest.add(pkg)
            manifest.write_to_s3(adapter)
            outputs.append(adapter._storage[PACKAGES_GZ_KEY])

        assert outputs[0] == outputs[1]

    def test_packages_gz_header_mtime_is_zero(self, written):
        """The gzip header mtime field is zeroed for reproducibility."""
        _, adapter = written
        data = adapter._storage[PACKAGES_GZ_KEY]
        mtime = struct.unpack("<I", data[4:8])[0]
        assert mtime == 0, f"gzip header mtime should be 0, got {mtime}"

    def test_packages_gz_is_valid_gzip(self, written):
        """The deterministic Packages.gz still decompresses correctly."""
        _, adapter = written
        data = adapter._storage[PACKAGES_GZ_KEY]
        assert gzip.decompress(data).decode("utf-8").startswith("Package:")
